version: '3.4'

services:
  flask_app:
    build: .
    restart: always
    container_name: flask_app
    env_file:
      - .env
    ports:
     - '80:5000'
    links:
      - mysql

  mysql:
    restart: always
    image: mariadb:10.4.13
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    volumes:
      - "./mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/mysqlsampledatabase.sql:z"
